after/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("my_app/", include("my_app.urls")),
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", view=views.index, name="index"),
]

my_app/urls.py
from django.urls import path

from my_app import views

app_name = "my_app"
urlpatterns = [
    path("cars", view=views.cars, name="car-list"),
    path("car/add", view=views.create_cars, name="car-add"),
]

home/models.py
from django.db import models

# Create your models here.

my_app/models.py
from django.db import models

class Car(models.Model):
    brand = models.CharField(max_length=20)
    model = models.IntegerField()

    def __str__(self):
        return f"{self.brand} | {self.model}"


class House(models.Model):
    owner = models.CharField(max_length=30)
    address = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.owner} | {self.address}"

my_app/forms.py
from django import forms


class CarForm(forms.Form):
    brand = forms.CharField(
        label="Marca:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "car-brand",
                "placeholder": "marca del coche",
                "required": "True",
            }
        ),
    )
    model = forms.IntegerField(
        label="Modelo:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "car-model",
                "placeholder": "modelo",
                "required": "True",
            }
        ),
    )

home/views.py
from django.shortcuts import render

def index(request):
    return render(
        request=request,
        context={},
        template_name="home/index.html",
    )

my_app/views.py
from django.contrib import messages
from django.shortcuts import render

from my_app.models import Car
from my_app.forms import CarForm


def create_cars(request):
    if request.method == "POST":
        car_form = CarForm(request.POST)
        print("-------------------------------------+++++++++++++++++")
        if car_form.is_valid():
            data = car_form.cleaned_data
            actual_objects = Car.objects.filter(
                brand=data["brand"], model=data["model"]
            ).count()
            print("actual_objects", actual_objects)
            if actual_objects:
                messages.error(
                    request,
                    f"El coche {data['brand']} - {data['model']} ya está creado",
                )
            else:
                car = Car(brand=data["brand"], model=data["model"])
                car.save()
                messages.success(
                    request,
                    f"Coche {data['brand']} - {data['model']} creado exitosamente!",
                )

            return render(
                request=request,
                context={"cars": Car.objects.all()},
                template_name="my_app/car_list.html",
            )

    car_form = CarForm(request.POST)
    context_dict = {"form": car_form}
    return render(
        request=request,
        context=context_dict,
        template_name="my_app/car_form.html",
    )


def cars(request):
    return render(
        request=request,
        context={"cars": Car.objects.all()},
        template_name="my_app/car_list.html",
    )

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% load static %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'home/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'home/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface_own
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'my_app:car-list' %}" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Cars</span>
                </a>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Houses</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">


        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </nav>

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
                        <a href="{% url 'my_app:car-add'  %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                            class="fas fa-download fa-sm text-white-50"></i> Crear Car</a>
                    </div>

                    <div class="row">
                        {% if messages %}
                        {% for message in messages %}
                            <div class="alert {{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                        <!-- Divider-->
                        <hr class="my-4" />
                        {% endif %}
                    </div>
                    
                        
                    {% block after_content %}
                        
                    <!-- Content Row -->
                    <div class="row">1

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-primary shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                                Earnings (Monthly)</div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                        
                    {% endblock %}
                        
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="js/demo/chart-area-demo.js"></script>
    <script src="js/demo/chart-pie-demo.js"></script>

</body>

</html>

my_app/templates/my_app/car_form.html
{% extends "home/index.html" %}
{% load static %}


{% block after_content %}

<div>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Guardar coche" />
    </form>
</div>

<!-- Divider-->
<hr/>

{% endblock %}

my_app/templates/my_app/car_list.html
{% extends "home/index.html" %}
{% load static %}


{% block after_content %}

{% for car in cars %}
    <!-- Post preview-->
    <div class="card-body">
        <h2>La marca del coche {{ car.brand }}</h2>
        <h3>modelo: {{ car.model }}</h3>
    </div>
    <!-- Divider-->
    <hr/>
{% endfor %}

{% endblock %}